blank_issues_enabled: true
contact_links:
  - name: ğŸ” Report a Security Vulnerability
    url: https://github.com/keploy/keploy/security/policy
    about: Please report sensitive bugs or vulnerabilities here.
